name: Scala / Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup JDK
        uses: actions/setup-java@v6.0.0
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Run tests for all exercises
        run: bin/test
